name: WorldGameMode
main: com.moosemanstudios.WorldGameMode.WorldGameMode
version: 1.1
commands:
    wgm:
        description: parent command for the sub commands
permissions:
    wgm.admin:
        description: allows changing of the world mode and reload config
    wgm.list:
        description: display list of worlds and hte mode they are in currently
    wgm.mode:
        description: allows player to change there mode regardless of worlds mode
